name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Clone helpers
      run: git clone --depth 1 --branch enh_summary git://github.com/klauer/pcds-ci-helpers.git

    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Initialize
      run: |
          export TWINCAT_SUMMARY=1
          bash pcds-ci-helpers/travis/tc3_summary.sh > project_summary.txt
                    
    - uses: actions/upload-artifact@v1
      with:
        name: project_summary.txt
        path: project_summary.txt
